version: '3.1'

services:

  database:
    image: 'postgres:11.5-alpine'
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
