version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      DATABASE_HOST: database
    depends_on:
      - database

  database:
    image: 'postgres:11.5-alpine'
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
    volumes:
      - my_volume:/var/lib/postgresql/data

volumes:
  my_volume:
