#!/usr/bin/env bash

#docker build -t posgresqldb .
#docker run --rm -p 8080:8080 -d posgresqldb
#docker stop $(docker ps -q --filter ancestor=posgresqldb) > /dev/null

docker-compose down f docker-compose.local.yml
docker-compose up -d -f docker-compose.local.yml
docker-compose logs -f database
